container:
  image: gradle:jdk8

compile_task:
  gradle_cache:
    folder: ~/.gradle/caches
  compile_script: gradle classes testClasses
  cleanup_before_cache_script:
    - rm -rf ~/.gradle/caches/$GRADLE_VERSION/
    - find ~/.gradle/caches/ -name "*.lock" -type f -delete
