container:
  image: gradle:jdk8

env:
  BINTRAY_API_KEY: ENCRYPTED[ae657ac6e6bd155cd5fb4edf9875f57577a74f18aee69a57ef2a32cbb9d19131907a3d223cca94be880aa8c96a579166]

compile_task:
  gradle_cache:
    folder: ~/.gradle/caches
  compile_script: gradle classes testClasses
  publish_script: ./scripts/publish.sh
  cleanup_before_cache_script:
    - rm -rf ~/.gradle/caches/$GRADLE_VERSION/
    - find ~/.gradle/caches/ -name "*.lock" -type f -delete
